filebeat.inputs:
- type: filestream
  id: snort-alert
  enabled: true
  paths:
    - /var/log/snort/alert
  fields:
    log_type: snort_alert
  fields_under_root: true

output.logstash:
  hosts: ["127.0.0.1:5044"]
