input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => {
      "message" => [
        "%{MONTHNUM:month}/%{MONTHDAY:day}-%{TIME:time}\s+\[\*\*\]\s+\[%{INT:gid}:%{INT:sid}:%{INT:rev}\]\s+%{DATA:alert_message}\s+\[\*\*\]\s+\[Priority:\s+%{INT:priority}\]\s+\{%{WORD:proto}\}\s+%{IP:src_ip}:%{INT:src_port}\s+->\s+%{IP:dst_ip}:%{INT:dst_port}",
        "%{MONTHNUM:month}/%{MONTHDAY:day}-%{TIME:time}\s+\[\*\*\]\s+\[%{INT:gid}:%{INT:sid}:%{INT:rev}\]\s+%{DATA:alert_message}\s+\[\*\*\]\s+\[Priority:\s+%{INT:priority}\]\s+\{%{WORD:proto}\}\s+%{IP:src_ip}\s+->\s+%{IP:dst_ip}"
      ]
    }
  }

  mutate {
    convert => {
      "priority" => "integer"
      "gid" => "integer"
      "sid" => "integer"
      "rev" => "integer"
    }
  }

  if [src_port] and [dst_port] {
    mutate {
      convert => {
        "src_port" => "integer"
        "dst_port" => "integer"
      }
    }
  }

  date {
    match => ["message", "MM/dd-HH:mm:ss.SSSSSS", "MM/dd-HH:mm:ss"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://10.81.12.36:9200"]
    index => "ids-snort-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
